package entity;
// Generated 03/02/2015 1:18:42 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name="Album"
    ,schema="dbo"
    ,catalog="MyPlaylist"
)
public class Album  implements java.io.Serializable {


     private String id;
     private String name;
     private String image;

    public Album() {
    }

    public Album(String id, String name, String image) {
       this.id = id;
       this.name = name;
       this.image = image;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="Name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="Image", nullable=false, length=250)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


