package entity;
// Generated 03/02/2015 1:18:42 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Artist generated by hbm2java
 */
@Entity
@Table(name="Artist"
    ,schema="dbo"
    ,catalog="MyPlaylist"
)
public class Artist  implements java.io.Serializable {


     private int id;
     private String name;
     private String image;

    public Artist() {
    }

	
    public Artist(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Artist(int id, String name, String image) {
       this.id = id;
       this.name = name;
       this.image = image;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="Image", length=250)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


