package entity;
// Generated 03/02/2015 1:18:42 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Record generated by hbm2java
 */
@Entity
@Table(name="Record"
    ,schema="dbo"
    ,catalog="MyPlaylist"
)
public class Record  implements java.io.Serializable {


     private int recordId;
     private String url;

    public Record() {
    }

    public Record(int recordId, String url) {
       this.recordId = recordId;
       this.url = url;
    }
   
     @Id 
    
    @Column(name="RecordId", unique=true, nullable=false)
    public int getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(int recordId) {
        this.recordId = recordId;
    }
    
    @Column(name="URL", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


