package entity;
// Generated 03/02/2015 1:18:42 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Song generated by hbm2java
 */
@Entity
@Table(name="Song"
    ,schema="dbo"
    ,catalog="MyPlaylist"
)
public class Song  implements java.io.Serializable {


     private String id;
     private String title;
     private String artist;
     private long weekPlayCount;
     private long playCount;
     private String category;

    public Song() {
    }

	
    public Song(String id, String title, String artist, long weekPlayCount, long playCount) {
        this.id = id;
        this.title = title;
        this.artist = artist;
        this.weekPlayCount = weekPlayCount;
        this.playCount = playCount;
    }
    public Song(String id, String title, String artist, long weekPlayCount, long playCount, String category) {
       this.id = id;
       this.title = title;
       this.artist = artist;
       this.weekPlayCount = weekPlayCount;
       this.playCount = playCount;
       this.category = category;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="Title", nullable=false, length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="Artist", nullable=false, length=50)
    public String getArtist() {
        return this.artist;
    }
    
    public void setArtist(String artist) {
        this.artist = artist;
    }
    
    @Column(name="WeekPlayCount", nullable=false)
    public long getWeekPlayCount() {
        return this.weekPlayCount;
    }
    
    public void setWeekPlayCount(long weekPlayCount) {
        this.weekPlayCount = weekPlayCount;
    }
    
    @Column(name="PlayCount", nullable=false)
    public long getPlayCount() {
        return this.playCount;
    }
    
    public void setPlayCount(long playCount) {
        this.playCount = playCount;
    }
    
    @Column(name="Category", length=50)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


